/* DATA CONFIG - Backend team replaces this with API calls */
// This file now imports from centralized mock data for consistency

export {
  APP_CONFIG,
  SUMMARY_DATA,
  MEMBERS as MEMBER_DATA,
  MEMBERS,
  ACTION_BUTTONS,
  TABLE_COLUMNS,
  GROUP_CONFIG,
  LOANS,
  CONTRIBUTIONS,
  LOAN_REPAYMENTS,
  LOAN_PURPOSE_OPTIONS,
  REPAYMENT_PERIOD_OPTIONS,
  ROLE_OPTIONS,
  CONTRIBUTION_DAY_OPTIONS,
  POOL_TOTAL,
  MAX_LOAN_AMOUNT,
  MIN_LOAN_AMOUNT,
  YEAR_END_REPORT,
  MOCK_GROUPS,
} from '../../data/mockData';